version: "2"
services:
  nginx:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - fpm
    volumes_from:
      - src
  fpm:
    build:
      context: ./conf/fpm
      dockerfile: Dockerfile
    volumes_from:
      - src
  src:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /var/www/html