version: "3"
services:
  nginx:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - fpm
    volumes:
      - source:/var/www/html
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - source:/var/www/html
volumes:
  source: {}